# name: "CI - Test Features"
# on:
#   push:
#     branches:
#       - main
#   pull_request:
#   workflow_dispatch:

# jobs:
#   test:
#     runs-on: ubuntu-latest
#     continue-on-error: false
#     steps:
#       - uses: actions/checkout@v3

#       - name: Setup latest Alpine Linux
#         uses: jirutka/setup-alpine@v1

#       - name: "Install latest devcontainer CLI"
#         run: npm install -g @devcontainers/cli

#       - name: "Test"
#         run: /github/workspace/test/node-alpine/test.sh
#         shell: alpine.sh {0}
